#!/bin/bash

echo "🔐 Vercel CLIでログインしてデプロイ"
echo "===================================="
echo ""
echo "手順："
echo "1. 以下のコマンドを実行："
echo ""
echo "   vercel login"
echo ""
echo "2. メールアドレスを入力"
echo "3. 確認メールのリンクをクリック"
echo "4. ログイン完了後、以下を実行："
echo ""
echo "   vercel --prod"
echo ""
echo "または、Vercelダッシュボードで："
echo ""
echo "1. Settings → Git → Disconnect"
echo "2. プロジェクトを削除"
echo "3. https://vercel.com/new から新規作成"
echo "4. onephotolife/my-board-app を選択"
echo "5. Deploy"
echo ""
echo "----------------------------------------"
echo "現在の状況："
echo "- GitHubには最新コード（1ea1dd7）がある ✅"
echo "- Vercelは古いコード（fbe78db）を使っている ❌"
echo "- Deploy Hookが機能していない ❌"
echo "----------------------------------------"