name: Codex: Command Dispatch
on:
  issue_comment:
    types: [created]
permissions:
  contents: read
  actions: write
jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '@codex run')
    steps:
      - name: Parse command
        id: parse
        run: |
          body="${{ github.event.comment.body }}"
          if echo "$body" | grep -qi "run bench"; then MODE=bench;
          elif echo "$body" | grep -qi "run e2e"; then MODE=e2e;
          else MODE=all; fi
          BRANCH=$(echo "$body" | sed -nE 's/.*branch=([^ ]+).*/\1/p')
          if [ -z "$BRANCH" ]; then BRANCH="main"; fi
          echo "mode=$MODE" >> $GITHUB_OUTPUT
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
      - name: Trigger Bench & E2E
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: .github/workflows/codex-bench-e2e.yml
          ref: ${{ github.ref }}
          inputs: |
            mode=${{ steps.parse.outputs.mode }}
            target_ref=${{ steps.parse.outputs.branch }}
